name: Sync Fork Main Branch

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Required to push changes to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v4
        with:
          repository: Enielect/creationary-frontend # Replace with your repo details
          token: ${{ secrets.WORKFLOW_TOKEN }}
          fetch-depth: 0 # Fetch all history for accurate diffing

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/iamr0b0tx/creationary-frontend
          git fetch upstream

      - name: Check for differences and sync
        run: |
          git checkout --track origin/main
          UPSTREAM_HASH=$(git rev-parse upstream/main)
          FORK_HASH=$(git rev-parse main)

          if [ "$UPSTREAM_HASH" != "$FORK_HASH" ]; then
            echo "Upstream main is ahead of fork main. Syncing..."
            git merge upstream/main --no-edit # Merge upstream changes
            git push origin main
            echo "Fork main synced successfully."
          else
            echo "Fork main is already in sync with upstream main."
          fi
