name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
      - uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/iamr0b0tx/creationary-frontend/
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: main
          # Branch to merge into downstream
          downstream_branch: main 
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}
            
